apiVersion: v1
kind: Service
metadata:
  name: journalapp-svc
  labels:
    app: journalapp-api
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
  selector:
    app: journalapp-api
