apiVersion: apps/v1
kind: Deployment
metadata:
  name: journalapp-canary
  labels:
    app: journalapp-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: journalapp-api
  template:
    metadata:
      labels:
        app: journalapp-api
        env: canary
    spec:
      containers:
      - name: journalapp
        image: hafizbadrie/journalapp:v0.2
        ports:
        - containerPort: 8080
