apiVersion: apps/v1
kind: Deployment
metadata:
  name: journalapp-dep
  labels:
    app: journalapp-api
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 50%
  selector:
    matchLabels:
      app: journalapp-api
  template:
    metadata:
      labels:
        app: journalapp-api
    spec:
      containers:
      - name: journalapp
        image: hafizbadrie/journalapp:v0.1
        ports:
        - containerPort: 8080
